name: greenhouse
version: "1.0.0"
config-version: 2
profile: greenhouse
model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  greenhouse:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table