spark.sql.session.timeZone         UTC
spark.sql.shuffle.partitions       8
spark.jars                        /opt/spark/jars/postgresql-42.7.3.jar
spark.serializer                  org.apache.spark.serializer.KryoSerializer
spark.driver.memory               1g
spark.executor.memory             1g
spark.driver.extraJavaOptions     -Duser.timezone=UTC
spark.executor.extraJavaOptions   -Duser.timezone=UTC